import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "tertiary-container": "#002113",
        "on-primary-container": "#7c839b",
        "outline-variant": "#c6c6cd",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#131b2e",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "outline": "#76777d",
        "secondary-fixed": "#dbe1ff",
        "primary": "#000000",
        "tertiary-fixed-dim": "#4edea3",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "on-secondary-fixed-variant": "#003ea8",
        "secondary-container": "#316bf3",
        "inverse-primary": "#bec6e0",
        "on-secondary-fixed": "#00174b",
        "primary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#565e74",
        "tertiary": "#000000",
        "surface-container-high": "#e6e8ea",
        "secondary": "#0051d5",
        "on-tertiary-fixed": "#002113",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "background": "#f7f9fb",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-container": "#009668",
        "on-secondary-container": "#fefcff",
        "on-primary-fixed-variant": "#3f465c",
        "error": "#ba1a1a",
        "primary-fixed": "#dae2fd",
        "on-background": "#191c1e",
        "surface-container": "#eceef0",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface-variant": "#45464d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "24px",
        "margin-mobile": "16px",
        base: "8px",
        gutter: "24px",
        "margin-desktop": "48px",
        "stack-lg": "48px",
        "stack-sm": "12px",
      },
      fontFamily: {
        "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "title-md": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "display-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
